import { createServer } from 'node:http';
import { createReadStream } from 'node:fs';
import { readFile, mkdtemp, rm } from 'node:fs/promises';
import { spawn, spawnSync } from 'node:child_process';
import { extname, join, normalize } from 'node:path';
import { tmpdir } from 'node:os';
const root=process.cwd(),mime=new Map([['.html','text/html; charset=utf-8'],['.js','text/javascript; charset=utf-8'],['.css','text/css; charset=utf-8']]),sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
function chrome(){for(const n of ['google-chrome','google-chrome-stable','chromium','chromium-browser']){const r=spawnSync('which',[n],{encoding:'utf8'});if(r.status===0&&r.stdout.trim())return r.stdout.trim();}throw new Error('Chromium required.');}
async function port(dir,p){const f=join(dir,'DevToolsActivePort');for(let i=0;i<500;i+=1){if(p.exitCode!==null)throw new Error('Chromium exited');try{const n=Number((await readFile(f,'utf8')).split(/\r?\n/)[0]);if(n>0)return n;}catch{}await sleep(50);}throw new Error('DevTools timeout');}
async function target(base){for(let i=0;i<200;i+=1){try{const xs=await(await fetch(`${base}/json/list`)).json();const p=xs.find(x=>x.type==='page'&&x.webSocketDebuggerUrl);if(p)return p;}catch{}await sleep(50);}throw new Error('No target');}
async function connect(url){const s=new WebSocket(url);await new Promise((r,j)=>{s.addEventListener('open',r,{once:true});s.addEventListener('error',j,{once:true});});let id=0;const q=new Map();s.addEventListener('message',e=>{const m=JSON.parse(String(e.data));if(!m.id||!q.has(m.id))return;const x=q.get(m.id);q.delete(m.id);m.error?x.reject(new Error(m.error.message)):x.resolve(m.result||{});});const send=(method,params={})=>new Promise((resolve,reject)=>{const rid=++id;q.set(rid,{resolve,reject});s.send(JSON.stringify({id:rid,method,params}));});return{socket:s,send};}
async function ev(c,e){const r=await c.send('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text||'eval');return r.result?.value;}
async function stop(p){if(!p||p.exitCode!==null)return;p.kill('SIGTERM');await sleep(300);if(p.exitCode===null)p.kill('SIGKILL');}
const server=createServer((req,res)=>{const raw=decodeURIComponent((req.url||'/').split('?')[0]),rel=raw==='/'?'/calibration.html':raw,file=normalize(join(root,rel));if(!file.startsWith(root))return res.writeHead(403).end();res.setHeader('Content-Type',mime.get(extname(file))||'application/octet-stream');const s=createReadStream(file);s.on('error',()=>res.writeHead(404).end());s.pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const {port:serverPort}=server.address();const work=await mkdtemp(join(tmpdir(),'ft-cal-gate-')),profile=join(work,'profile');let proc,cdp;
try{proc=spawn(chrome(),['--headless=new','--no-sandbox','--disable-gpu','--remote-debugging-port=0',`--user-data-dir=${profile}`,`http://127.0.0.1:${serverPort}/calibration.html`],{stdio:'ignore'});const dp=await port(profile,proc),page=await target(`http://127.0.0.1:${dp}`);cdp=await connect(page.webSocketDebuggerUrl);await cdp.send('Runtime.enable');
let gate;for(let i=0;i<100;i+=1){gate=await ev(cdp,`({gate:!!document.querySelector('.ft-calibration-gate'),unlocked:document.documentElement.dataset.calibrationUnlocked,home:document.querySelector('.ft-calibration-gate a[href="./index.html"]')?.textContent})`);if(gate?.gate)break;await sleep(50);}if(!gate?.gate||gate.unlocked==='true'||gate.home!=='HOME')throw new Error(`Calibration soft gate missing: ${JSON.stringify(gate)}`);
await ev(cdp,`(() => { const input=document.querySelector('[data-calibration-password]'); input.value='FUTOLTECH-RD'; document.querySelector('.ft-calibration-gate form').requestSubmit(); })()`);let unlocked;for(let i=0;i<100;i+=1){unlocked=await ev(cdp,`({unlocked:document.documentElement.dataset.calibrationUnlocked,gate:!!document.querySelector('.ft-calibration-gate'),home:document.querySelector('.status-cluster a[href="./index.html"]')?.textContent,title:document.querySelector('h1')?.textContent})`);if(unlocked?.unlocked==='true')break;await sleep(50);}if(unlocked?.unlocked!=='true'||unlocked.gate||unlocked.home!=='HOME'||unlocked.title!=='Test Data Validation')throw new Error(`Calibration unlock/home contract failed: ${JSON.stringify(unlocked)}`);console.log('Calibration soft R&D access gate and HOME navigation QA passed.');
}finally{try{cdp?.socket.close();}catch{}await stop(proc);await new Promise(r=>server.close(r));await rm(work,{recursive:true,force:true});}
