import { createServer } from 'node:http';
import { createReadStream } from 'node:fs';
import { readFile, mkdtemp, rm } from 'node:fs/promises';
import { spawn, spawnSync } from 'node:child_process';
import { extname, join, normalize } from 'node:path';
import { tmpdir } from 'node:os';

const CASE = process.argv[2] ?? 'all';
const VALID_CASES = new Set(['all','rigid','brace','spring','pdelta','redistribution']);
if (!VALID_CASES.has(CASE)) throw new Error(`Unknown Frame Analyzer QA case: ${CASE}`);
const root = process.cwd();
const mime = new Map([['.html','text/html; charset=utf-8'],['.js','text/javascript; charset=utf-8'],['.css','text/css; charset=utf-8']]);
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function findChrome(){for(const name of ['google-chrome','google-chrome-stable','chromium','chromium-browser']){const r=spawnSync('which',[name],{encoding:'utf8'});if(r.status===0&&r.stdout.trim())return r.stdout.trim();}throw new Error('Headless Chromium/Chrome is required for Frame Analyzer QA.');}
async function waitPort(profileDir,proc){const file=join(profileDir,'DevToolsActivePort');for(let i=0;i<500;i+=1){if(proc.exitCode!==null)throw new Error(`Chromium exited early: ${proc.exitCode}`);try{const port=Number((await readFile(file,'utf8')).trim().split(/\r?\n/)[0]);if(port>0)return port;}catch{}await sleep(50);}throw new Error('Timed out waiting for Chromium DevTools port.');}
async function pageTarget(base){for(let i=0;i<200;i+=1){try{const targets=await(await fetch(`${base}/json/list`)).json();const page=targets.find((t)=>t.type==='page'&&t.webSocketDebuggerUrl);if(page)return page;}catch{}await sleep(50);}throw new Error('Frame Analyzer Chromium target did not appear.');}
async function cdpOpen(url){const socket=new WebSocket(url);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});let id=0;const pending=new Map();socket.addEventListener('message',(event)=>{const msg=JSON.parse(String(event.data));if(!msg.id||!pending.has(msg.id))return;const req=pending.get(msg.id);pending.delete(msg.id);msg.error?req.reject(new Error(msg.error.message)):req.resolve(msg.result||{});});const send=(method,params={})=>new Promise((resolve,reject)=>{const requestId=++id;pending.set(requestId,{resolve,reject});socket.send(JSON.stringify({id:requestId,method,params}));});return{socket,send};}
async function evaluate(cdp,expression){const r=await cdp.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails){const detail=r.exceptionDetails.exception?.description||r.exceptionDetails.text||'Browser evaluation failed.';throw new Error(detail);}return r.result?.value;}
async function stop(proc){if(!proc||proc.exitCode!==null)return;proc.kill('SIGTERM');await sleep(500);if(proc.exitCode===null)proc.kill('SIGKILL');}
const server=createServer((req,res)=>{const raw=decodeURIComponent((req.url||'/').split('?')[0]),rel=raw==='/'?'/frame.html':raw,file=normalize(join(root,rel));if(!file.startsWith(root))return res.writeHead(403).end('Forbidden');res.setHeader('Content-Type',mime.get(extname(file))||'application/octet-stream');const stream=createReadStream(file);stream.on('error',()=>res.writeHead(404).end('Not found'));stream.pipe(res);});
await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));
const {port}=server.address();

async function waitForSelector(cdp, selector, label) {
  for (let i=0;i<60;i+=1) {
    const exists=await evaluate(cdp,`!!document.querySelector(${JSON.stringify(selector)})`);
    if(exists)return;
    await sleep(50);
  }
  throw new Error(`${label}: expected control ${selector} did not appear after rerender.`);
}

async function selectSpringJoint(cdp, caseName) {
  await evaluate(cdp,`(() => { const jt=document.querySelector('#frameJointTypeSelect'); if(!jt) throw new Error('joint type control missing'); jt.value='spring'; jt.dispatchEvent(new Event('change',{bubbles:true})); })()`);
  await waitForSelector(cdp,'#frameSpringStiffnessInput',caseName);
  await evaluate(cdp,`(() => { const input=document.querySelector('#frameSpringStiffnessInput'); if(!input) throw new Error('spring stiffness control missing'); input.value='10'; input.dispatchEvent(new Event('input',{bubbles:true})); })()`);
}

async function withFreshFramePage(caseName,fn){const work=await mkdtemp(join(tmpdir(),`ft-frame-${caseName}-`)),profile=join(work,'profile');let chromeProcess,cdp;try{chromeProcess=spawn(findChrome(),['--headless=new','--disable-gpu','--no-sandbox','--disable-dev-shm-usage','--remote-debugging-port=0',`--user-data-dir=${profile}`,`http://127.0.0.1:${port}/frame.html?build=ci-${caseName}`],{stdio:'ignore'});const debugPort=await waitPort(profile,chromeProcess),target=await pageTarget(`http://127.0.0.1:${debugPort}`);cdp=await cdpOpen(target.webSocketDebuggerUrl);await cdp.send('Runtime.enable');let ready=false;for(let i=0;i<120;i+=1){const state=await evaluate(cdp,`({ready:document.readyState,state:document.documentElement.dataset.frameState,cards:document.querySelectorAll('#frameResultCards .result-card').length})`);if(state?.ready==='complete'&&state.state==='analyzed'&&state.cards>=6){ready=true;break;}await sleep(100);}if(!ready)throw new Error(`${caseName}: NF-001 default frame did not become ready.`);await fn(cdp);}finally{try{cdp?.socket.close();}catch{}await stop(chromeProcess);await rm(work,{recursive:true,force:true});}}

async function rigidCase(){await withFreshFramePage('rigid',async(cdp)=>{const s=await evaluate(cdp,`({banner:document.querySelector('#frameStateBanner').textContent,trace:document.querySelector('#frameCalculationTrace').textContent,diagram:document.querySelectorAll('#frameDiagram .frame-member-deformed').length,error:document.querySelector('#frameErrorBanner').textContent})`);if(!/FIRST-ORDER ELASTIC/.test(s.banner))throw new Error(`rigid: default state missing: ${s.banner}`);if(!/ΣFx:[\s\S]*?residual\s*-?0(?:\.0+)?\s*kN/.test(s.trace)||!/ΣFy:[\s\S]*?residual\s*-?0(?:\.0+)?\s*kN/.test(s.trace))throw new Error(`rigid: equilibrium trace is not balanced: ${s.trace}`);if(s.diagram!==3)throw new Error(`rigid: expected 3 deformed members, found ${s.diagram}`);if(s.error.trim())throw new Error(`rigid: unexpected error: ${s.error}`);});console.log('NF-001 rigid Chromium QA passed.');}

async function braceCase(){await withFreshFramePage('brace',async(cdp)=>{await evaluate(cdp,`(() => { const brace=document.querySelector('#frameBraceSelect');brace.value='N1-N4';brace.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#frameBraceEInput').value='13100';document.querySelector('#frameBraceAreaInput').value='2500';document.querySelector('#frameRunButton').click(); })()`);await sleep(320);const s=await evaluate(cdp,`({adviser:document.querySelector('#frameBraceAdviser').textContent,evidence:document.querySelector('#frameBraceEvidence').textContent,diagram:document.querySelectorAll('#frameDiagram .frame-member-deformed').length,braceLines:document.querySelectorAll('#frameDiagram .frame-brace-deformed').length,error:document.querySelector('#frameErrorBanner').textContent})`);if(!/STIFFNESS SENSITIVITY ONLY/.test(s.adviser)||!/capacity UNRATED/i.test(s.adviser))throw new Error(`brace: boundary missing: ${s.adviser}`);const reduction=Number(s.adviser.match(/Elastic drift reduction:\s*([\d.]+)%/)?.[1]);if(!(reduction>0))throw new Error(`brace: positive drift reduction missing: ${s.adviser}`);if(!/UNVERIFIED SENSITIVITY/.test(s.evidence))throw new Error(`brace: arbitrary E/A not labeled sensitivity: ${s.evidence}`);if(s.diagram!==4||s.braceLines!==1)throw new Error(`brace: expected 4 members / 1 brace: ${JSON.stringify(s)}`);if(s.error.trim())throw new Error(`brace: unexpected error: ${s.error}`);});console.log('NF-001 brace-sensitivity Chromium QA passed.');}

async function springCase(){await withFreshFramePage('spring',async(cdp)=>{await selectSpringJoint(cdp,'spring');await evaluate(cdp,`document.querySelector('#frameRunButton').click()`);await sleep(300);const s=await evaluate(cdp,`({evidence:document.querySelector('#frameJointEvidence').textContent,connections:document.querySelectorAll('#frameConnectionBody tr').length,body:document.querySelector('#frameConnectionBody').textContent,error:document.querySelector('#frameErrorBanner').textContent})`);if(!/UNVERIFIED SENSITIVITY/.test(s.evidence))throw new Error(`spring: kθ not labeled sensitivity: ${s.evidence}`);if(s.connections!==4||!/10 kN·m\/rad/.test(s.body))throw new Error(`spring: expected four 10 kN·m/rad springs: ${s.body}`);if(s.error.trim())throw new Error(`spring: unexpected error: ${s.error}`);});console.log('NF-001 semi-rigid Chromium QA passed.');}

async function pdeltaCase(){await withFreshFramePage('pdelta',async(cdp)=>{await selectSpringJoint(cdp,'pdelta');await evaluate(cdp,`(() => { const analysis=document.querySelector('#frameAnalysisSelect');analysis.value='pdelta';analysis.dispatchEvent(new Event('change',{bubbles:true})); })()`);await waitForSelector(cdp,'#frameGravityLoadInput','pdelta');await evaluate(cdp,`(() => { document.querySelector('#frameGravityLoadInput').value='50';document.querySelector('#frameRunButton').click(); })()`);await sleep(400);const s=await evaluate(cdp,`({banner:document.querySelector('#frameStateBanner').textContent,cards:document.querySelector('#frameResultCards').textContent,error:document.querySelector('#frameErrorBanner').textContent,frameState:document.documentElement.dataset.frameState})`);if(s.frameState!=='analyzed')throw new Error(`pdelta: analysis did not complete: ${JSON.stringify(s)}`);if(!/SECOND-ORDER ELASTIC P–Δ/.test(s.banner)||!/P–Δ amplification/.test(s.cards))throw new Error(`pdelta: state missing: ${JSON.stringify(s)}`);if(s.error.trim())throw new Error(`pdelta: unexpected error: ${s.error}`);});console.log('NF-001 P-Delta Chromium QA passed.');}

async function redistributionCase(){await withFreshFramePage('redistribution',async(cdp)=>{await selectSpringJoint(cdp,'redistribution');await evaluate(cdp,`(() => { const analysis=document.querySelector('#frameAnalysisSelect');analysis.value='redistribution';analysis.dispatchEvent(new Event('change',{bubbles:true})); })()`);await waitForSelector(cdp,'#frameMomentLimitInput','redistribution');await waitForSelector(cdp,'#frameResidualRatioInput','redistribution');await evaluate(cdp,`(() => { document.querySelector('#frameMomentLimitInput').value='0.001';document.querySelector('#frameResidualRatioInput').value='0.2';document.querySelector('#frameRunButton').click(); })()`);await sleep(450);const s=await evaluate(cdp,`({banner:document.querySelector('#frameStateBanner').textContent,events:document.querySelectorAll('#frameRedistributionEvents .frame-event').length,text:document.querySelector('#frameRedistributionEvents').textContent,interpretation:document.querySelector('#frameJointInterpretation').textContent,error:document.querySelector('#frameErrorBanner').textContent,frameState:document.documentElement.dataset.frameState})`);if(!s.frameState)throw new Error(`redistribution: analysis did not produce a state: ${JSON.stringify(s)}`);if(!/REDISTRIBUTION|MECHANISM/.test(s.banner)||s.events<1)throw new Error(`redistribution: explicit event did not occur: ${JSON.stringify(s)}`);if(!/does not infer them from fastener count/i.test(s.interpretation+s.text))throw new Error('redistribution: evidence boundary not visible.');if(s.error.trim())throw new Error(`redistribution: unexpected error: ${s.error}`);});console.log('NF-001 redistribution Chromium QA passed.');}

const cases={rigid:rigidCase,brace:braceCase,spring:springCase,pdelta:pdeltaCase,redistribution:redistributionCase};
try{if(CASE==='all')for(const name of ['rigid','brace','spring','pdelta','redistribution'])await cases[name]();else await cases[CASE]();}finally{await new Promise((resolve)=>server.close(resolve));}
